#!/bin/bash


SECRETPASSORD="monkeyshinedonut"
curl --user root:$SECRETPASSWORD --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listunspent", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:22555/
